apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-conf-1
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": "eth1",
      "mode": "l3",
      "ipam": {
        "type": "host-local",
        "subnet": "10.10.5.0/24",
        "rangeStart": "10.10.5.2",
        "rangeEnd": "10.10.5.80",
        "gateway": "10.10.5.1"
      }
    }'