apiVersion: v1
kind: Pod
metadata:
  name: multus-1-nic
  labels:
    app: miztiik-1-nic-app
  annotations:
      k8s.v1.cni.cncf.io/networks: ipvlan-conf-1
spec:
  containers:
  - name: multitool
    command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: busybox